services:
  heimdalld:
    build:
      context: ./polygon
      dockerfile: Dockerfile.heimdall
      args:
        - DOCKER_TAG=${HEIMDALL_TAG}
    image: heimdall:${NETWORK}
    pull_policy: never
#    tty: true
    user: root
    environment:
      - NETWORK=${NETWORK}
      - HEIMDALL_P2P_PORT=${HEIMDALL_P2P_PORT:-26656}
      - HEIMDALL_RPC_PORT=${HEIMDALL_RPC_PORT:-26657}
      - HEIMDALL_BOR_RPC_URL=${HEIMDALL_BOR_RPC_URL}
      - HEIMDALL_ETH_RPC_URL=${HEIMDALL_ETH_RPC_URL}
      - HEIMDALL_SEEDS=${HEIMDALL_SEEDS}
      - BOR_NODE_ID=${BOR_NODE_ID}
      - ENABLE_PROMETHEUS_METRICS=true
      - LOG_LEVEL=${LOG_LEVEL}
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      default:
        aliases:
          - ${NETWORK}-heimdalld # This allows multiple Polygon Docker stacks all connected to the same central traefik
    entrypoint:
      - docker-entrypoint.sh
      - heimdalld
      - start
      - --home
      - /var/lib/heimdall
      - --chain
      - ${NETWORK}
      - --rest-server
    volumes:
      - heimdall-data:/var/lib/heimdall
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HEIMDALL_P2P_PORT:-26656}:${HEIMDALL_P2P_PORT:-26656}/tcp
    labels:
      - metrics.scrape=true
      - metrics.port=26660
      - metrics.path=/metrics

  bor:
    image: bor:${NETWORK}
    pull_policy: never
    build:
      context: ./polygon
      dockerfile: ${BOR_DOCKER_FILE}
      args:
        - BUILD_TARGET=${BOR_SRC_TAG}
        - DOCKER_TAG=${BOR_TAG}
    restart: unless-stopped
    stop_grace_period: 3m
    user: root
    environment:
      - NETWORK=${NETWORK}
      - BOR_DIR=/var/lib/bor
      - BOR_BOOTNODES=${BOR_BOOTNODES}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - USE_ARIA=${USE_ARIA:-true}
      - TRUSTED_NODES=${BOR_TRUSTED_NODES:-}
      - EXTRAS=${BOR_EXTRAS:-}
    networks:
      default:
        aliases:
          - ${NETWORK}-bor # This allows multiple Polygon Docker stacks all connected to the same central traefik
    entrypoint:
      - docker-entrypoint.sh
      - --datadir
      - /var/lib/bor/data
      - --cache
      - ${BOR_CACHE}
      - --ws
      - --ws.port
      - ${BOR_WS_PORT}
      - --ws.addr
      - 0.0.0.0
      - --ws.origins=*
      - --ws.api
      - eth,net,web3,txpool,bor
      - --port
      - ${BOR_P2P_PORT}
      - --metrics
      - --metrics.prometheus-addr
      - 0.0.0.0:6060
      - --metrics.expensive
      - --metrics.opencollector-endpoint
      - ""
      - --txpool.locals
      - ${TX_LOCAL_ADDR}
      - --txpool.globalslots
      - "400000"
      - --rpc.txfeecap
      - "0"
      - --txpool.accountslots
      - "256"
      - --bor.heimdall
      - http://${NETWORK}-heimdalld:1317
      - --txpool.accountqueue
      - "64"
      - --txpool.globalqueue
      - "131072"
      - --txpool.pricelimit
      - "30000000000"
      - --maxpeers
      - "200"
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.api
      - eth,net,web3,txpool,bor
      - --http.port
      - ${BOR_RPC_PORT}
      - --chain
      - ${NETWORK}
      - --ethstats
      - ${BOR_NODE_ID}:${NETWORK}@bor-${NETWORK}.vitwit.com:3000
    volumes:
      - bor-data:/var/lib/bor
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "${BOR_RPC_PORT}/tcp"
      - "${BOR_WS_PORT}/tcp"
    ports:
      - ${BOR_P2P_PORT}:${BOR_P2P_PORT}/tcp
      - ${BOR_P2P_PORT}:${BOR_P2P_PORT}/udp
    labels:
      - metrics.scrape=true
      - metrics.port=6060
      - metrics.path=/debug/metrics/prometheus
      - traefik.enable=true
      - traefik.http.routers.bor-${EL_HOST}.service=bor-${EL_HOST}
      - traefik.http.routers.bor-${EL_HOST}.entrypoints=websecure
      - traefik.http.routers.bor-${EL_HOST}.rule=Host(`${EL_HOST}.${DOMAIN}`)
      - traefik.http.routers.bor-${EL_HOST}.tls.certresolver=letsencrypt
      - traefik.http.routers.borlb-${EL_HOST}.service=bor-${EL_HOST}
      - traefik.http.routers.borlb-${EL_HOST}.entrypoints=websecure
      - traefik.http.routers.borlb-${EL_HOST}.rule=Host(`${EL_LB}.${DOMAIN}`)
      - traefik.http.routers.borlb-${EL_HOST}.tls.certresolver=letsencrypt
      - traefik.http.services.bor-${EL_HOST}.loadbalancer.server.port=${BOR_RPC_PORT}
      - traefik.http.routers.borws-${EL_WS_HOST}.service=-${EL_WS_HOST}
      - traefik.http.routers.borws-${EL_WS_HOST}.entrypoints=websecure
      - traefik.http.routers.borws-${EL_WS_HOST}.rule=Host(`${EL_WS_HOST}.${DOMAIN}`)
      - traefik.http.routers.borws-${EL_WS_HOST}.tls.certresolver=letsencrypt
      - traefik.http.routers.borwslb-${EL_WS_HOST}.service=borws-${EL_WS_HOST}
      - traefik.http.routers.borwslb-${EL_WS_HOST}.entrypoints=websecure
      - traefik.http.routers.borwslb-${EL_WS_HOST}.rule=Host(`${EL_WS_LB}.${DOMAIN}`)
      - traefik.http.routers.borwslb-${EL_WS_HOST}.tls.certresolver=letsencrypt
      - traefik.http.services.borws-${EL_WS_HOST}.loadbalancer.server.port=${BOR_WS_PORT}

  set-prune-marker:
    profiles: ["tools"]
    image: alpine:latest
    user: "10001:10001"
    restart: "no"
    volumes:
      - bor-data:/var/lib/bor
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  bor-data:
  heimdall-data:
