services:
  heimdalld:
    build:
      context: ./polygon
      dockerfile: Dockerfile.heimdall
      args:
        - DOCKER_TAG=${HEIMDALL_TAG}
        - DOCKER_REPO=${HEIMDALL_REPO}
    image: heimdall:${NETWORK}
    pull_policy: never
#    tty: true
    user: root
    environment:
      - NETWORK=${NETWORK}
      - HEIMDALL_P2P_PORT=${HEIMDALL_P2P_PORT:-26656}
      - HEIMDALL_RPC_PORT=${HEIMDALL_RPC_PORT:-26657}
      - HEIMDALL_BOR_RPC_URL=${HEIMDALL_BOR_RPC_URL}
      - HEIMDALL_ETH_RPC_URL=${HEIMDALL_ETH_RPC_URL}
      - HEIMDALL_SEEDS=${HEIMDALL_SEEDS}
      - HEIMDALL_PEERS=${HEIMDALL_PEERS}
      - BOR_NODE_ID=${BOR_NODE_ID}
      - ENABLE_PROMETHEUS_METRICS=true
      - LOG_LEVEL=${LOG_LEVEL}
      - SNAPSHOT=${HEIMDALL_SNAPSHOT}
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      default:
        aliases:
          - ${NETWORK}-heimdalld # This allows multiple Polygon Docker stacks all connected to the same central traefik
    entrypoint:
      - docker-entrypoint.sh
      - heimdalld
      - start
      - --home
      - /var/lib/heimdall
      - --chain
      - ${NETWORK}
      - --rest-server
    volumes:
      - heimdall-data:/var/lib/heimdall
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HEIMDALL_P2P_PORT:-26656}:${HEIMDALL_P2P_PORT:-26656}/tcp
    labels:
      - metrics.scrape=true
      - metrics.port=26660
      - metrics.path=/metrics
      - metrics.network=polygon-${NETWORK}

  bor:
    image: bor:${NETWORK}
    pull_policy: never
    build:
      context: ./polygon
      dockerfile: ${BOR_DOCKER_FILE}
      args:
        - BUILD_TARGET=${BOR_SRC_TAG}
        - DOCKER_TAG=${BOR_TAG}
        - DOCKER_REPO=${BOR_REPO}
    restart: unless-stopped
    stop_grace_period: 3m
    user: root
    environment:
      - NETWORK=${NETWORK}
      - BOR_DIR=/var/lib/bor
      - BOR_BOOTNODES=${BOR_BOOTNODES}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - USE_ARIA=${USE_ARIA:-true}
      - TRUSTED_NODES=${BOR_TRUSTED_NODES:-}
      - EXTRAS=${BOR_EXTRAS:-}
      - SNAPSHOT=${BOR_SNAPSHOT}
    networks:
      default:
        aliases:
          - ${NETWORK}-bor # This allows multiple Polygon Docker stacks all connected to the same central traefik
    entrypoint:
      - docker-entrypoint.sh
      - --datadir
      - /var/lib/bor/data
      - --cache
      - ${BOR_CACHE}
      - --ws
      - --ws.port
      - ${BOR_WS_PORT}
      - --ws.addr
      - 0.0.0.0
      - --ws.origins=*
      - --ws.api
      - eth,net,web3,txpool,bor
      - --port
      - ${BOR_P2P_PORT}
      - --metrics
      - --metrics.prometheus-addr
      - 0.0.0.0:6060
      - --metrics.opencollector-endpoint
      - ""
      - --txpool.locals
      - ${TX_LOCAL_ADDR}
      - --txpool.globalslots
      - "400000"
      - --rpc.txfeecap
      - "0"
      - --txpool.accountslots
      - "256"
      - --bor.heimdall
      - http://${NETWORK}-heimdalld:1317
      - --txpool.accountqueue
      - "64"
      - --txpool.globalqueue
      - "131072"
      - --txpool.pricelimit
      - "30000000000"
      - --maxpeers
      - "200"
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.api
      - eth,net,web3,txpool,bor
      - --http.port
      - ${BOR_RPC_PORT}
      - --chain
      - ${NETWORK}
      - --ethstats
      - ${BOR_NODE_ID}:${NETWORK}@bor-${NETWORK}.vitwit.com:3000
    volumes:
      - bor-data:/var/lib/bor
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "${BOR_RPC_PORT}/tcp"
      - "${BOR_WS_PORT}/tcp"
    ports:
      - ${BOR_P2P_PORT}:${BOR_P2P_PORT}/tcp
      - ${BOR_P2P_PORT}:${BOR_P2P_PORT}/udp
    labels:
      - metrics.scrape=true
      - metrics.port=6060
      - metrics.path=/debug/metrics/prometheus
      - metrics.network=polygon-${NETWORK}
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-polygon}.service=${RPC_HOST:-polygon}
      - traefik.http.routers.${RPC_HOST:-polygon}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-polygon}.rule=Host(`${RPC_HOST:-polygon}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-polygon}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-polygon}lb.service=${RPC_HOST:-polygon}
      - traefik.http.routers.${RPC_HOST:-polygon}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-polygon}lb.rule=Host(`${RPC_LB:-polygon-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-polygon}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-polygon}.loadbalancer.server.port=${BOR_RPC_PORT:-8545}
      - traefik.http.routers.${WS_HOST:-polygonws}.service=${WS_HOST:-polygonws}
      - traefik.http.routers.${WS_HOST:-polygonws}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-polygonws}.rule=Host(`${WS_HOST:-polygonws}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-polygonws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-polygonws}lb.service=${WS_HOST:-polygonws}
      - traefik.http.routers.${WS_HOST:-polygonws}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-polygonws}lb.rule=Host(`${WS_LB:-polygonws-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-polygonws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-polygonws}.loadbalancer.server.port=${BOR_WS_PORT:-8546}

  set-prune-marker:
    profiles: ["tools"]
    image: alpine:latest
    user: "10001:10001"
    restart: "no"
    volumes:
      - bor-data:/var/lib/bor
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  bor-data:
  heimdall-data:
